server:
  port : 8000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: 1st-service-get
          #          uri: http://localhost:52070/

          # ??? ? ???? ???(?, application name? ??(??? ??? ????? ?? ?? ??? ??))
          uri: lb://1ST-SERVICE

          # ????? ??? ??? ?? ???? ???(??? ???)
          predicates:
            - Path=/first-service/**

          # ?? ??? ? ???? ???? /first-serivce?? ???? ???? ?? ????? ???? ? + ?? ??
          # ???? built in ?? + custom ??(feat.spring security) ?? ??
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}

        - id: 2st-service-get
          uri: lb://2ND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7861/eureka

