server:
  port: 8761
eureka:
  client:

    # eureka server는 eureka server에서 관리할 필요가 없다.
    register-with-eureka: false

    # eureka server는 자기 자신을 30초 단위로 주기적으로 인지할 필요가 없다.1
    fetch-registry: false
