server:
  port: 7861
eureka:
  client:

    # eureka server\uB294 eureka server\uC5D0\uC11C \uAD00\uB9AC\uD560 \uD544\uC694\uAC00 \uC5C6\uB2E4.
    register-with-eureka: false

    # eureka server\uB294 \uC790\uAE30 \uC790\uC2E0\uC744 30\uCD08 \uB2E8\uC704\uB85C \uC8FC\uAE30\uC801\uC73C\uB85C \uC778\uC9C0\uD560 \uD544\uC694\uAC00 \uC5C6\uB2E4.1
    fetch-registry: false
